apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-simple-app
  template:
    metadata:
      labels:
        app: my-simple-app
    spec:
      containers:
      - name: app
        image: <DOCKERHUB_USERNAME>/my-simple-app:latest
        ports:
        - containerPort: 3000