name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Minikube
      run: |
        sudo apt-get update
        sudo apt-get install -y conntrack
        minikube start --driver=docker
        minikube update-context
        kubectl config view
        
    - name: Apply manifests
      run: |
        # Получаем реальный IP кластера
        API_SERVER=$(kubectl config view -o jsonpath='{.clusters[0].cluster.server}')
        echo "API Server: $API_SERVER"
        
        # Применяем манифесты с явным указанием сервера
        kubectl apply -f k8s/ --server=$API_SERVER --validate=false
        
        # Проверяем статус
        kubectl get pods
        kubectl get svc